version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: line-provider_service
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - aerich
    volumes:
      - .:/app
    command: bash -c "uvicorn line_provider.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - bsw_network

  db:
    image: postgres:15-alpine
    container_name: line-provider_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - line-provider_app-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - bsw_network

  aerich:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: line-provider_aerich
    entrypoint: /app/scripts/aerich.sh
    restart: "no"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bsw_network

volumes:
  line-provider_app-db-data:

networks:
  bsw_network:
    external: true
