version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bet-maker_service
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
      - aerich
    volumes:
      - .:/app
    command: bash -c "uvicorn bet_maker.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - bsw_network

  db:
    image: postgres:15-alpine
    container_name: bet-maker_db
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - bet-maker_app-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - bsw_network

  aerich:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bet-maker_aerich
    entrypoint: /app/scripts/aerich.sh
    restart: "no"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bsw_network

volumes:
  bet-maker_app-db-data:

networks:
  bsw_network:
    external: true